config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'
  resources :categories
  resources :games
  resources :users
  resources :posts

  #Se logado como ADM  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/comprar/:id', to: 'games#comprar_game', as: :comprar_game
  #lista jogos comprados
  get 'livraria', to: 'users#my_games'
  #Troca de games    
#  get 'transferencia', to 'users_helper#trans_my_game'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    mount_uploader :picture, ImageUploader
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]   


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comprar_game   
    #Passa pro new os parametros
    @my_games = MyGame.new(user: current_user, game_id: params[:id])     
    #Se salvo faça    
    if @my_games.save
      redirect_to games_path      
    end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :price, :picture)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">    
    <%= form.file_field :picture %>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4">InSteam Black Week</h1>
  <hr class="my-4">
  <p class="lead">de 20 até 98% de desconto em todos os jogos do ano</p>
</div>


<div class="container mb-5 mt-5">
  <div class="pricing card-deck flex-column flex-md-row mb-3">
    <% @games.each do |game| %>
      <div class="card card-pricing popular shadow text-center px-3 mb-4" style="background: url(<%= game.picture %>)">
        <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white shadow-sm">
          <%= game.name %>
        </span>
        <div class="bg-transparent card-header pt-4 border-0">
          
        </div>
        <div class="card-body pt-0">
          <ul class="list-unstyled mb-4">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
          <button class="btn btn-dark btn-lg mb-3">
            <%= link_to 'Comprar', game %>
          </button>
        </div>
        <h1 class="h1 font-weight-normal text-light text-center mb-0" data-pricing-value="30">R$
            <span class="price"><%= game.price %></span>            
          </h1>
      </div>
      <% end %>
  </div>
</div>



<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %> 
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>
<!--Dois pontos : siginifica que vamos pegar uma chave -> <%= params[:id] %>-->
<!--Verifica se é Admin da Plataforma-->
 <% if current_user.email == 'abel@id.uff.br' %>
  <%= link_to 'Edit', edit_game_path(@game) %> |
  <%= link_to 'Back', games_path %>
<% else %>  
  <td><%= link_to 'Comprar', comprar_game_path(@game.id), method: :post %></td>  
<% end %>

<p>
  <strong>Picture:</strong>   
  <%= image_tag @game.picture.url %>
  
</p>