config/routes.rb
Rails.application.routes.draw do  
  get 'sessions/new'
  resources :categories
  resources :games
  resources :users
  resources :posts

  #Se logado como ADM  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post '/comprar/:id', to: 'games#comprar_game', as: :comprar_game
  #lista jogos comprados
  get 'livraria', to: 'users#my_games'
  #Troca de games    
#  get 'transferencia', to 'users_helper#trans_my_game'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InSteam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--CND Bootstrap 4-->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
    <div class="container-fluid">
    
        <a class="navbar-brand" href="#"><%= link_to "InSteam", users_path %></a>
        
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
               
            </ul>           
            <% if logged_in? %>
              <% primeiroNome = current_user.name.split(" ") %>              
                <ul class="nav navbar-nav flex-row justify-content-between ml-auto text-white">
                    <li><%= primeiroNome[0].capitalize %></li>             
                    <li><%= link_to "Loja", games_path %></li>
                    <li><%= link_to "Promoções", current_user %></li>
                    <li><%= link_to "Minhas Trocas", current_user %></li>
                    <li><%= link_to "Biblioteca", "livraria" %></li>
                    <li><%= link_to "Perfil", current_user %></li>
                    <li><%= link_to "Sair", logout_path, method: :delete %></h4></li>              
                </ul>
            <% end %>
        </div>
    </div>
</nav>

<div id="modalPassword" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Forgot password</h3>
                <button type="button" class="close font-weight-light" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <p>Reset your password..</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                <button class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

    
  <%= yield %>
  </body>
  <!--Javascript CDN-->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>